### ISSUE TITLE
Why I cannot see unfollower?

### ISSUE THREAD

**Issue by bcExpt1123** [Sorosliu1029/follower-change#10]
Here is my workflow script.
```
name: follower notifier
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: get follower change
        id: followerChange
        uses: Sorosliu1029/follower-change@v2
        with:
          myToken: ${{ secrets.MY_TOKEN }}
          notifyUnFollowEvent: false
      - name: email me
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_HOST }}
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Follower Change
          from: '"Github Follower Notifier" <bcexpt1123@gmail.com>'
          to: bcexpt1123@gmail.com
          html_body: file://${{ steps.followerChange.outputs.htmlFilePath }}
```

Here is a follower and an unfollower. But I cannot see unfollower in the email notification.
![Image](https://github.com/user-attachments/assets/0acb84b8-19ae-4a17-a2ef-12a17f1ca81d)

I've attached a screenshot for my email view.
![Image](https://github.com/user-attachments/assets/5f5873ff-d89e-4d27-9ec2-b346d5872abb)
